site_name: Odoo Turbo Caché Importer
site_author: BenjaminDTS
site_description: Módulo de importación masiva con precarga en RAM (Eager Loading)

theme:
  name: material
  features:
    - navigation.sections
    - navigation.top

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            show_root_heading: true
            heading_level: 2
            docstring_style: sphinx # Compatible con el formato usado